// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/movie.proto

package moviepb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type MovieReq struct {
	Pagination           string   `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
	Searchword           string   `protobuf:"bytes,2,opt,name=searchword,proto3" json:"searchword,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MovieReq) Reset()         { *m = MovieReq{} }
func (m *MovieReq) String() string { return proto.CompactTextString(m) }
func (*MovieReq) ProtoMessage()    {}
func (*MovieReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_78364ce9948b3a40, []int{0}
}

func (m *MovieReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MovieReq.Unmarshal(m, b)
}
func (m *MovieReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MovieReq.Marshal(b, m, deterministic)
}
func (m *MovieReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MovieReq.Merge(m, src)
}
func (m *MovieReq) XXX_Size() int {
	return xxx_messageInfo_MovieReq.Size(m)
}
func (m *MovieReq) XXX_DiscardUnknown() {
	xxx_messageInfo_MovieReq.DiscardUnknown(m)
}

var xxx_messageInfo_MovieReq proto.InternalMessageInfo

func (m *MovieReq) GetPagination() string {
	if m != nil {
		return m.Pagination
	}
	return ""
}

func (m *MovieReq) GetSearchword() string {
	if m != nil {
		return m.Searchword
	}
	return ""
}

type MovieRes struct {
	Title                string   `protobuf:"bytes,1,opt,name=Title,proto3" json:"Title,omitempty"`
	Year                 string   `protobuf:"bytes,2,opt,name=Year,proto3" json:"Year,omitempty"`
	ImdbID               string   `protobuf:"bytes,3,opt,name=imdbID,proto3" json:"imdbID,omitempty"`
	Type                 string   `protobuf:"bytes,4,opt,name=Type,proto3" json:"Type,omitempty"`
	Poster               string   `protobuf:"bytes,5,opt,name=Poster,proto3" json:"Poster,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MovieRes) Reset()         { *m = MovieRes{} }
func (m *MovieRes) String() string { return proto.CompactTextString(m) }
func (*MovieRes) ProtoMessage()    {}
func (*MovieRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_78364ce9948b3a40, []int{1}
}

func (m *MovieRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MovieRes.Unmarshal(m, b)
}
func (m *MovieRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MovieRes.Marshal(b, m, deterministic)
}
func (m *MovieRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MovieRes.Merge(m, src)
}
func (m *MovieRes) XXX_Size() int {
	return xxx_messageInfo_MovieRes.Size(m)
}
func (m *MovieRes) XXX_DiscardUnknown() {
	xxx_messageInfo_MovieRes.DiscardUnknown(m)
}

var xxx_messageInfo_MovieRes proto.InternalMessageInfo

func (m *MovieRes) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *MovieRes) GetYear() string {
	if m != nil {
		return m.Year
	}
	return ""
}

func (m *MovieRes) GetImdbID() string {
	if m != nil {
		return m.ImdbID
	}
	return ""
}

func (m *MovieRes) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *MovieRes) GetPoster() string {
	if m != nil {
		return m.Poster
	}
	return ""
}

type GetMovieReq struct {
	Movie                *MovieReq `protobuf:"bytes,1,opt,name=movie,proto3" json:"movie,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *GetMovieReq) Reset()         { *m = GetMovieReq{} }
func (m *GetMovieReq) String() string { return proto.CompactTextString(m) }
func (*GetMovieReq) ProtoMessage()    {}
func (*GetMovieReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_78364ce9948b3a40, []int{2}
}

func (m *GetMovieReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetMovieReq.Unmarshal(m, b)
}
func (m *GetMovieReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetMovieReq.Marshal(b, m, deterministic)
}
func (m *GetMovieReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMovieReq.Merge(m, src)
}
func (m *GetMovieReq) XXX_Size() int {
	return xxx_messageInfo_GetMovieReq.Size(m)
}
func (m *GetMovieReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMovieReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetMovieReq proto.InternalMessageInfo

func (m *GetMovieReq) GetMovie() *MovieReq {
	if m != nil {
		return m.Movie
	}
	return nil
}

type GetMovieRes struct {
	Search               []*MovieRes `protobuf:"bytes,1,rep,name=Search,proto3" json:"Search,omitempty"`
	TotalResults         string      `protobuf:"bytes,2,opt,name=totalResults,proto3" json:"totalResults,omitempty"`
	Response             string      `protobuf:"bytes,3,opt,name=Response,proto3" json:"Response,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *GetMovieRes) Reset()         { *m = GetMovieRes{} }
func (m *GetMovieRes) String() string { return proto.CompactTextString(m) }
func (*GetMovieRes) ProtoMessage()    {}
func (*GetMovieRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_78364ce9948b3a40, []int{3}
}

func (m *GetMovieRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetMovieRes.Unmarshal(m, b)
}
func (m *GetMovieRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetMovieRes.Marshal(b, m, deterministic)
}
func (m *GetMovieRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMovieRes.Merge(m, src)
}
func (m *GetMovieRes) XXX_Size() int {
	return xxx_messageInfo_GetMovieRes.Size(m)
}
func (m *GetMovieRes) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMovieRes.DiscardUnknown(m)
}

var xxx_messageInfo_GetMovieRes proto.InternalMessageInfo

func (m *GetMovieRes) GetSearch() []*MovieRes {
	if m != nil {
		return m.Search
	}
	return nil
}

func (m *GetMovieRes) GetTotalResults() string {
	if m != nil {
		return m.TotalResults
	}
	return ""
}

func (m *GetMovieRes) GetResponse() string {
	if m != nil {
		return m.Response
	}
	return ""
}

func init() {
	proto.RegisterType((*MovieReq)(nil), "proto.MovieReq")
	proto.RegisterType((*MovieRes)(nil), "proto.MovieRes")
	proto.RegisterType((*GetMovieReq)(nil), "proto.GetMovieReq")
	proto.RegisterType((*GetMovieRes)(nil), "proto.GetMovieRes")
}

func init() { proto.RegisterFile("proto/movie.proto", fileDescriptor_78364ce9948b3a40) }

var fileDescriptor_78364ce9948b3a40 = []byte{
	// 281 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x8f, 0x4d, 0x4b, 0xc3, 0x40,
	0x10, 0x86, 0xa9, 0x6d, 0x4a, 0x9c, 0x56, 0x8a, 0x83, 0xc8, 0xd2, 0x83, 0x94, 0x80, 0xe8, 0xa9,
	0x42, 0xf4, 0xe6, 0xad, 0x08, 0xa2, 0x20, 0xc8, 0xb6, 0x17, 0xbd, 0x25, 0xed, 0xa0, 0x0b, 0x69,
	0x36, 0xee, 0xae, 0x51, 0xff, 0xbd, 0x64, 0x76, 0x1b, 0x23, 0x3d, 0x65, 0xde, 0x8f, 0x99, 0xcd,
	0x03, 0xc7, 0x95, 0xd1, 0x4e, 0x5f, 0x6d, 0x75, 0xad, 0x68, 0xce, 0x33, 0x46, 0xfc, 0x49, 0x1e,
	0x21, 0x7e, 0x6a, 0x5c, 0x49, 0x1f, 0x78, 0x06, 0x50, 0x65, 0x6f, 0xaa, 0xcc, 0x9c, 0xd2, 0xa5,
	0xe8, 0xcd, 0x7a, 0x97, 0x87, 0xb2, 0xe3, 0x34, 0xb9, 0xa5, 0xcc, 0xac, 0xdf, 0xbf, 0xb4, 0xd9,
	0x88, 0x03, 0x9f, 0xff, 0x39, 0xc9, 0x77, 0x7b, 0xcb, 0xe2, 0x09, 0x44, 0x2b, 0xe5, 0x0a, 0x0a,
	0x67, 0xbc, 0x40, 0x84, 0xc1, 0x0b, 0x65, 0x26, 0xec, 0xf2, 0x8c, 0xa7, 0x30, 0x54, 0xdb, 0x4d,
	0xfe, 0x70, 0x27, 0xfa, 0xec, 0x06, 0xd5, 0x74, 0x57, 0x3f, 0x15, 0x89, 0x81, 0xef, 0x36, 0x73,
	0xd3, 0x7d, 0xd6, 0xd6, 0x91, 0x11, 0x91, 0xef, 0x7a, 0x95, 0xdc, 0xc0, 0xe8, 0x9e, 0x5c, 0x0b,
	0x72, 0x0e, 0x11, 0xa3, 0xf2, 0xe3, 0xa3, 0x74, 0xe2, 0x91, 0xe7, 0xbb, 0x5c, 0xfa, 0x34, 0xa9,
	0xbb, 0x5b, 0x16, 0x2f, 0x60, 0xb8, 0x64, 0x18, 0xd1, 0x9b, 0xf5, 0xf7, 0xd7, 0xac, 0x0c, 0x31,
	0x26, 0x30, 0x76, 0xda, 0x65, 0x85, 0x24, 0xfb, 0x59, 0x38, 0x1b, 0x68, 0xfe, 0x79, 0x38, 0x85,
	0x58, 0x92, 0xad, 0x74, 0x69, 0x29, 0x70, 0xb5, 0x3a, 0x5d, 0xc0, 0x98, 0x6f, 0x2e, 0xc9, 0xd4,
	0x6a, 0x4d, 0x98, 0x42, 0xbc, 0xfb, 0x0f, 0xc4, 0xf0, 0x68, 0x07, 0x67, 0xba, 0xef, 0xd9, 0xc5,
	0xe4, 0xf5, 0x88, 0xcd, 0x5b, 0x46, 0xa9, 0xf2, 0x7c, 0xc8, 0xf2, 0xfa, 0x37, 0x00, 0x00, 0xff,
	0xff, 0x0a, 0x22, 0xc9, 0xc9, 0xeb, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MovieServiceClient is the client API for MovieService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MovieServiceClient interface {
	GetMovie(ctx context.Context, in *GetMovieReq, opts ...grpc.CallOption) (*GetMovieRes, error)
}

type movieServiceClient struct {
	cc *grpc.ClientConn
}

func NewMovieServiceClient(cc *grpc.ClientConn) MovieServiceClient {
	return &movieServiceClient{cc}
}

func (c *movieServiceClient) GetMovie(ctx context.Context, in *GetMovieReq, opts ...grpc.CallOption) (*GetMovieRes, error) {
	out := new(GetMovieRes)
	err := c.cc.Invoke(ctx, "/proto.MovieService/GetMovie", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MovieServiceServer is the server API for MovieService service.
type MovieServiceServer interface {
	GetMovie(context.Context, *GetMovieReq) (*GetMovieRes, error)
}

func RegisterMovieServiceServer(s *grpc.Server, srv MovieServiceServer) {
	s.RegisterService(&_MovieService_serviceDesc, srv)
}

func _MovieService_GetMovie_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMovieReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MovieServiceServer).GetMovie(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.MovieService/GetMovie",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MovieServiceServer).GetMovie(ctx, req.(*GetMovieReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _MovieService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.MovieService",
	HandlerType: (*MovieServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetMovie",
			Handler:    _MovieService_GetMovie_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/movie.proto",
}
